version: "3.5"

services:

  mongo: 
    image: mongo:latest 
    container_name: blog-mongo
    #restart: "no"
    env_file: 
      - .env
    environment: 
#      - "MONGO_INITDB_ROOT_USERNAME=${DB_USER}"
#      - "MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}"
      - "MONGO_INITDB_DATABASE=blogProject"
      - "MONGO_INITDB_ROOT_USERNAME=brian"
      - "MONGO_INITDB_ROOT_PASSWORD=wong"
    networks: 
      - blog
    ports:
      - '27017:27017'

  blog-api:
     build: . # build the local DockerFile
     image: blog-api:latest #name the Docker image as such
     container_name: blog-api
     restart: unless-stopped
     depends_on:
      - mongo
     networks:
      - blog
     ports:
      - '3000:3000'

networks:
  blog:
    name: blog-backend
    driver: bridge
